---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-1
  labels:
    k8s.ovn.org/primary-user-defined-network: ""
    purpose: multi-tenancy-demo
    user: tenant-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-1-proxy
  labels:
    purpose: multi-tenancy-demo
    user: tenant-1
---
apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: tenant-1-dp
  namespace: tenant-1
  labels:
    purpose: multi-tenancy-demo
    user: tenant-1
spec:
  topology: Layer3
  layer3:
    role: Primary
    subnets:
      - cidr: "10.102.0.0/16"
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: tenant-1-cp
  labels:
    purpose: multi-tenancy-demo
    user: tenant-1
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["tenant-1", "tenant-1-cp-system"]
  network:
    topology: Layer2
    layer2:
      role: Secondary
      subnets:
       - "104.104.0.0/16"
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: tenant-1-external
  labels:
    purpose: multi-tenancy-demo
    user: tenant-1
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["tenant-1", "tenant-1-proxy"]
  network:
    topology: Layer2
    layer2:
      role: Secondary
      subnets:
       - "105.105.0.0/16"



